export const ENUMS = {
  USER_TYPES: ["admin", "user"] as const,
  DEVICE_TYPES: ["web", "android", "ios"] as const,
  USER_STATUS: ["active", "inactive", "blocked", "deleted", "reported"] as const,
  NOTIFICATION_STATUS: ["on", "off", "mute"] as const,
  LOCATION_STATUS: ["on", "off"] as const,
  SIGNUP_THROUGH: ["Google", "Facebook", "Web"] as const,
  NOTIFICATION_TYPES: [
    "message",
    "payment",
    "alert",
    "system",
    "reminder",
    "invitation",
    "info",
    "conversation",
  ] as const,
  PRODUCT_CONDITIONS: [
    "collectible_acceptable",
    "collectible_good",
    "collectible_like_new",
    "collectible_very_good",
    "new_new",
    "new_oem",
    "new_open_box",
    "refurbished_refurbished",
    "used_acceptable",
    "used_good",
    "used_like_new",
    "used_very_good",
    "any",
  ] as const,
  APPLIES_TO_ORDER_TYPE: ["SALE", "REFUND", "REPLACEMENT", "ANY"] as const,
  AUTOMATION_TRIGGER_TYPES: [
    "ORDER_CREATED",
    "ORDER_STATUS_CHANGED",
    "TASK_COMPLETED",
    "TIME_BASED",
    "MANUAL",
    "WEBHOOK",
    "SCHEDULED",
  ] as const,
  TASK_CATEGORIES: [
    "ASSEMBLY",
    "TESTING",
    "SOFTWARE_INSTALL",
    "LOGISTICS",
    "CUSTOMER_SERVICE",
    "FINANCE",
    "INVENTORY",
    "AUTOMATION",
    "ADMINISTRATION",
    "OTHER",
  ] as const,
  // Order-related enums
  ORDER_TYPES: ["SALE", "REFUND", "REPLACEMENT"] as const,
  SOURCE_PLATFORMS: ["STOREFRONT", "EBAY", "AMAZON", "WALMART", "ETSY", "OTHER"] as const,
  ORDER_STATUSES: [
    "PENDING_PAYMENT",
    "PENDING_ADMIN_CONFIGURATION",
    "IN_PROGRESS",
    "SHIPPED",
    "DELIVERED",
    "COMPLETED",
    "CANCELLED",
    "ON_HOLD",
    "REFUNDED",
    "PARTIALLY_REFUNDED",
    "RETURN_INITIATED",
    "RETURN_RECEIVED",
    "REPLACED",
    // Legacy statuses for backward compatibility
    "Pending",
    "Processing",
    "Completed",
    "Canceled",
  ] as const,
  PAYMENT_STATUSES: [
    "PENDING",
    "PAID",
    "FAILED",
    "REFUNDED",
    "PARTIALLY_REFUNDED",
    "AUTHORIZED",
    "CAPTURED",
    "Completed",
  ] as const,
  REFUND_STATUSES: ["PENDING", "PROCESSED", "FAILED"] as const,
  SHIPPING_STATUSES: ["Pending", "Shipped", "Delivered"] as const,
  PRODUCT_CONDITIONS_ORDER: ["New", "Used", "Refurbished", "Open Box"] as const,
  DISCOUNT_TYPES: ["COUPON", "PROMOTION", "MANUAL"] as const,
};
