export const ENUMS = {
  USER_TYPES: ["admin", "user"] as const,
  DEVICE_TYPES: ["web", "android", "ios"] as const,
  USER_STATUS: ["active", "inactive", "blocked", "deleted", "reported"] as const,
  NOTIFICATION_STATUS: ["on", "off", "mute"] as const,
  LOCATION_STATUS: ["on", "off"] as const,
  SIGNUP_THROUGH: ["Google", "Facebook", "Web"] as const,
  NOTIFICATION_TYPES: [
    "message",
    "payment",
    "alert",
    "system",
    "reminder",
    "invitation",
    "info",
    "conversation",
  ] as const,
  PRODUCT_CONDITIONS: [
    "collectible_acceptable",
    "collectible_good",
    "collectible_like_new",
    "collectible_very_good",
    "new_new",
    "new_oem",
    "new_open_box",
    "refurbished_refurbished",
    "used_acceptable",
    "used_good",
    "used_like_new",
    "used_very_good",
    "any",
  ] as const,
  APPLIES_TO_ORDER_TYPE: ["SALE", "REFUND", "REPLACEMENT", "ANY"] as const,
  AUTOMATION_TRIGGER_TYPES: [
    "ORDER_CREATED",
    "ORDER_STATUS_CHANGED",
    "TASK_COMPLETED",
    "TIME_BASED",
    "MANUAL",
    "WEBHOOK",
    "SCHEDULED",
  ] as const,
  TASK_CATEGORIES: [
    "ASSEMBLY",
    "TESTING",
    "SOFTWARE_INSTALL",
    "LOGISTICS",
    "CUSTOMER_SERVICE",
    "FINANCE",
    "INVENTORY",
    "AUTOMATION",
    "ADMINISTRATION",
    "OTHER",
  ] as const,
};
